apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
  labels:
    app: consumer-microservice
spec:
  containers:
    - name: consumer-container
      image: nagendra9/iot-platform-consumer:0.1
      ports:
        - containerPort: 8082
