apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
  labels:
    app: producer-microservice
spec:
  containers:
    - name: producer-container
      image: nagendra9/iot-platform-producer:0.1
      ports:
        - containerPort: 8080
      env:
        - name: JWT_SECRET
          value: thesecretoftheuniverseisjwtthesecretoftheuniverseisjwtthesecretoftheuniverseisjwt
